In [55]:
import json
import numpy as np
from pathlib import Path
import matplotlib as mpl
# Use the pgf backend (must be set before pyplot imported)
mpl.use('pgf')

import matplotlib.pyplot as plt

In [4]:
exp_path = '/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/'

In [44]:
def get_exp_name(file_path):
    start_idx = len(exp_path) + 1
    end_idx = str(file_path).find('/', start_idx)
    return str(file_path)[start_idx:end_idx]

def get_run_number(file_path):
    substr = 'run'
    idx = str(file_path).find(substr) + len(substr)
    return str(file_path)[idx:idx+1]

def get_seed(file_path):
    substr = 'seed_'
    start_idx = str(file_path).find(substr) + len(substr)
    end_idx = str(file_path).find('_', start_idx)
    return int(str(file_path)[start_idx: end_idx])

def get_glob_seed_pattern(file_path):
    substr = 'seed_'
    start_idx = str(file_path).find(substr) + len(substr)
    end_idx = str(file_path).find('_', start_idx)
    return str(file_path)[:start_idx] + '?' + str(file_path)[end_idx:]

def clean_up_dict(data):
    new_data = {}
    for k, v in data.items():
        new_k = k.split('/')[-1]
        new_data[new_k] = v
    return new_data



In [39]:
a = 'aadssas/asadd/asd/sa'

a.split('/')[-1]

'sa'

In [42]:
file_paths = list(Path(exp_path).rglob("*.json"))
file_path = file_paths[0]
print(file_path)
with open(file_path) as json_file:
    data = json.load(json_file)
print(data.keys())

/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/summary.json
dict_keys(['/cluster/home/miperez/git/on-policy/onpolicy/scripts/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/value_loss/value_loss', '/cluster/home/miperez/git/on-policy/onpolicy/scripts/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/policy_loss/policy_loss', '/cluster/home/miperez/git/on-policy/onpolicy/scripts/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/dist_entropy/dist_entropy', '/cluster/home/miperez/git/on-policy/onpolicy/scripts/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/actor_grad_norm/actor_grad_norm', '/cluster/home/miperez/git/on-policy/onpolicy/scripts/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/

dict_keys(['value_loss', 'policy_loss', 'dist_entropy', 'actor_grad_norm', 'critic_grad_norm', 'ratio', 'wm_act_pred_loss', 'wm_obs_pred_loss', 'commitment_loss', 'average_episode_rewards', 'individual_rewards'])

In [47]:
file_paths = list(Path(exp_path).rglob("*.json"))

file_data = {}

for path in file_paths:
    glob_pattern = get_exp_name(get_glob_seed_pattern(path))
    seed = get_seed(path)
    with open(path) as json_file:
        data = json.load(json_file)
    data = clean_up_dict(data)
    if glob_pattern not in file_data.keys():
        file_data[glob_pattern] = {}
    file_data[glob_pattern][seed] = data


for exp_name, exp_data in file_data.items():
    for seed in exp_data.keys():
        print(f'{exp_name}, {seed}')

IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0, 0
IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0, 1
IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0, 2
IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0, 4
IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0, 3
IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0, 2
IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0, 3
IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0, 4
IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0, 0
IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0, 1
IS_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 0
IS_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 2
IS_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 1
IS_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 3
IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 2
IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 3
IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 4
IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 0
IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.01, 1
IS_IPPO_

In [52]:
len(file_data['IP_IPPO_local_seed_?_comm_int_26_commit_coef_0.1'][0]['value_loss'])

625

In [81]:
def get_stat_data(file_data):
    stat_data = {}

    for exp_name, exp_data in file_data.items():
        if exp_name not in stat_data.keys():
            stat_data[exp_name] = {}
        raw_data = {}
        for seed, seed_data in exp_data.items():
            for value_name, values in seed_data.items():
                if value_name not in raw_data.keys():
                    raw_data[value_name] = []
                raw_data[value_name].append(values)
        for value_name, values in raw_data.items():
            values = np.array(values)
            if value_name not in stat_data.keys():
                stat_data[exp_name][value_name] = {}
            stat_data[exp_name][value_name]['mean'] = np.mean(values[..., 2], axis=0)
            stat_data[exp_name][value_name]['std'] = np.std(values[..., 2], axis=0)
            for timesteps in values[..., 1]:
                assert np.all(values[0,:,1] == timesteps)
            stat_data[exp_name][value_name]['timestep'] = values[0, :, 1]
    return stat_data

IP_IPPO_local_seed_?_comm_int_26_commit_coef_1.0
------------------
value_loss - mean: [0.85053035 0.33275026 0.18915364 0.12659948 0.09808502 0.07780739
 0.08265892 0.07221371 0.07207903 0.07090827 0.06747375 0.05721551
 0.05235584 0.04773315 0.04981726 0.06029054 0.04938565 0.05366151
 0.0456626  0.04924045 0.05135318 0.04837011 0.04973047 0.04497437
 0.05391776 0.05133026 0.04594238 0.04562301 0.05053193 0.04799859
 0.04449897 0.05129727 0.04428352 0.04857387 0.05241785 0.05603677
 0.06506758 0.07562547 0.06753514 0.0697644  0.05944515 0.06260867
 0.06365896 0.06968035 0.07472419 0.07466108 0.07047686 0.05210556
 0.05156104 0.05264728 0.06037054 0.05571737 0.04741072 0.05175835
 0.05489856 0.05160703 0.05985293 0.06682344 0.09719158 0.07549169
 0.07895326 0.08111078 0.07271107 0.08158554 0.06499902 0.07408688
 0.07960999 0.06386001 0.06855853 0.06998573 0.07693676 0.06319182
 0.05285067 0.05895319 0.06044353 0.06144381 0.05640731 0.05483963
 0.06335261 0.06236604 0.06642911 0.067816

In [74]:
a = np.random.rand(5,3)
print(a)
for b in a:
    print(b)

[[0.72282152 0.65595295 0.48347967]
 [0.62541516 0.86858179 0.95303668]
 [0.63006828 0.26257594 0.76709876]
 [0.75177237 0.77716043 0.94300276]
 [0.5087541  0.431147   0.05528474]]
[0.72282152 0.65595295 0.48347967]
[0.62541516 0.86858179 0.95303668]
[0.63006828 0.26257594 0.76709876]
[0.75177237 0.77716043 0.94300276]
[0.5087541  0.431147   0.05528474]


In [24]:
file_paths

[PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_0_comm_int_26_commit_coef_1.0/run1/logs/summary.json'),
 PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IS_IPPO_local_seed_2_comm_int_1_commit_coef_0.0/run1/logs/summary.json'),
 PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IS_IPPO_local_seed_0_comm_int_26_commit_coef_0.01/run1/logs/summary.json'),
 PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IP_IPPO_local_seed_2_comm_int_26_commit_coef_0.01/run1/logs/summary.json'),
 PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IS_IPPO_local_seed_3_comm_int_1_commit_coef_0.0/run1/logs/summary.json'),
 PosixPath('/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IS_IPPO_local_seed_3_comm_int_26_commit_coef_0.0/run1/logs/summary.json'),
 PosixPath('/home/michel/own

In [26]:
file_path = file_paths[1]
file_name = get_exp_name(file_path)
substr = 'seed_'
start_idx = str(file_path).find(substr) + len(substr)
end_idx = str(file_path).find('_', start_idx)

str(file_path)[:start_idx] + '?' + str(file_path)[end_idx:]

'/home/michel/ownCloud/ETHZ/Master Thesis/results/MPE/simple_spread/crmappo/IS_IPPO_local_seed_?_comm_int_1_commit_coef_0.0/run1/logs/summary.json'

In [ ]:
with open('data.json') as json_file:
    data = json.load(json_file)

In [ ]:
plt.scatter(x, y, marker='x')
plt.savefig('norm.pgf', format='pgf')